### ISSUE TITLE
Using docker-akaunting behind ssl reverse proxy

### ISSUE THREAD

**Issue by JMyrng** [sameersbn/docker-akaunting#5]
Hi,

I´m trying to get the container working with an traefik reverse proxy in front of it. But I´m constantly running into "mixed content" issues. 
Akaunting is trying to get its content over http. What can I do to prevent this?

The docker-compose:

```
akaunting:
    restart: always
    image: sameersbn/akaunting:1.3.9
    container_name: akaunting
    command: app:akaunting
    environment:
      - DEBUG=true
      - TZ=Europe/Berlin
      - APP_LOCALE=de_DE
      - DB_HOST=xxx
      - DB_USER=xxx
      - DB_PASS=xxx
      - DB_NAME=xxx
      - AKAUNTING_URL=https://akaunting.xxx.xx
      - AKAUNTING_COMPANY_NAME=xxx xxx
      - AKAUNTING_COMPANY_EMAIL=xxx@xxx.xx
      - AKAUNTING_ADMIN_EMAIL=info@xxx.xx
      - AKAUNTING_ADMIN_PASSWORD=xxxxxxxxx
      - AKAUNTING_BACKUPS_EXPIRY=0
    volumes:
      - /opt/docker/akaunting/akaunting:/var/lib/akaunting
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
      - "traefik.enable=false"

  nginx:
    restart: always
    container_name: akaunting_nginx
    image: sameersbn/akaunting:1.3.9
    command: app:nginx
    environment:
      - AKAUNTING_PHP_FPM_HOST=akaunting
      - AKAUNTING_PHP_FPM_PORT=9000
    depends_on:
      - akaunting
    labels:
      - "traefik.enable=true"
      - "traefik.frontend.rule=Host:akaunting.xxx.xx"
      - "traefik.frontend.headers.customRequestHeaders=X-Forwarded-Proto:https||X-Forwarded-Port:443"
      - "traefik.port=80"
      - "com.centurylinklabs.watchtower.enable=true"  
```

docker version:
```
Client:
 Version:           18.09.7
 API version:       1.39
 Go version:        go1.10.1
 Git commit:        2d0083d
 Built:             Wed Jul  3 12:13:59 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.1
  Git commit:       2d0083d
  Built:            Mon Jul  1 19:31:12 2019
  OS/Arch:          linux/amd64
  Experimental:     false 
```

Greetings, 
mohrengemuse

**Comment by code4pay** [comment]
So what needs to happen is laravel needs to trust the proxy chain,   This requires a file `trustedproxies.php `   in  `/var/www/akaunting/config`   with the following contents
```
<?php

return [

    'proxies' => '**',
  
    'headers' => [
        (defined('Illuminate\Http\Request::HEADER_FORWARDED') ? Illuminate\Http\Request::HEADER_FORWARDED : 'forwarded') => 'FORWARDED',
        Illuminate\Http\Request::HEADER_CLIENT_IP    => 'X_FORWARDED_FOR',
        Illuminate\Http\Request::HEADER_CLIENT_HOST  => 'X_FORWARDED_HOST',
        Illuminate\Http\Request::HEADER_CLIENT_PROTO => 'X_FORWARDED_PROTO',
        Illuminate\Http\Request::HEADER_CLIENT_PORT  => 'X_FORWARDED_PORT',
    ]
];
```
This will get it working.

**Note** to add the file you can login to the image then run 
`cat >config/trustedproxies.php`
paste the file content into the terminal then `CTRL-d`

**Comment by timeens** [comment]
In my case (running akaunting behind TRAEFIK I had to make sure assets (.js, .css) are being loaded over HTTPS to get rid of the mixed content.

I have resolved this by adding `\URL::forceScheme('https');` to the `boot()` method in ` ./app/Providers/AppServiceProvider.php`.

The method results in:
`
    public function boot()
    {
        // Laravel db fix
        Schema::defaultStringLength(191);
        \URL::forceScheme('https');
    }
`

**Comment by stefanDeveloper** [comment]
@timeens I added it to the `AppServiceProvider.php` as well, but I still get  mixed content issues in my browser.

Is there anything else I have to configure?

**Comment by timeens** [comment]
@stefanDeveloper 

Hi Stefan, Try to use my docker image: https://hub.docker.com/repository/docker/timeens/akaunting-reverse-proxy

I adjusted this repo to work with my reverse proxy setup. Check the forked git repo to see the changes I made.

**Comment by stefanDeveloper** [comment]
@timeens Even with your image I get a mixed content issue

```
version: '2'

services:
  mysql:
    restart: always
    image: sameersbn/mysql:5.7.24
    environment:
      - DB_USER=akaunting
      - DB_PASS=PW
      - DB_NAME=akaunting_db
    volumes:
      - ./akaunting/mysql:/var/lib/mysql
    networks:
      - proxy

  akaunting:
    restart: always
    image: sameersbn/akaunting:1.3.9
    command: app:akaunting
    environment:
      - DEBUG=false
      - TZ=Asia/Kolkata

      - DB_HOST=mysql
      - DB_USER=akaunting
      - DB_PASS=PW
      - DB_NAME=akaunting_db

      - AKAUNTING_URL=http://localhost:10080

      - AKAUNTING_COMPANY_NAME=NAME
      - AKAUNTING_COMPANY_EMAIL=EMAIL

      - AKAUNTING_ADMIN_EMAIL=EMAIL
      - AKAUNTING_ADMIN_PASSWORD=PW

      - AKAUNTING_BACKUPS_EXPIRY=0
    depends_on:
      - mysql
    volumes:
      - ./akaunting/akaunting:/var/lib/akaunting
    networks:
      - proxy

  nginx:
    restart: always
    image: timeens/akaunting-reverse-proxy:latest
    command: app:nginx
    ports:
      - 10080:80
    environment:
      - AKAUNTING_PHP_FPM_HOST=akaunting
      - AKAUNTING_PHP_FPM_PORT=9000
    depends_on:
      - akaunting
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.finance.rule=Host(`finance.XXXX.XXX`)"
      - "traefik.http.routers.finance.entrypoints=websecure"
      - "traefik.http.routers.finance.tls.certresolver=mytlschallenge"
      - "traefik.http.services.finance.loadbalancer.server.port=10080"
    networks:
      - proxy

networks:
  proxy:
    external: true
```

Am I missing here something?

**Comment by timeens** [comment]
Try to use the image for all services and set the  AKAUNTING_URL=https://XXX.

This setup works for me on a docker swarm.

My compose file:

`
version: '3'

services:

  akaunting:
    image: timeens/akaunting-reverse-proxy:latest
    networks:
      - swarm
    command: app:akaunting
    hostname: akaunting
    environment:
    - DEBUG=false
    - TZ=xxx

    - DB_HOST=mysql
    - DB_USER=xxx
    - DB_PASS=xxx
    - DB_NAME=xxx

    - AKAUNTING_URL=https://xxx

    - AKAUNTING_COMPANY_NAME=xxx
    - AKAUNTING_COMPANY_EMAIL=xxx

    - AKAUNTING_ADMIN_EMAIL=xxx
    - AKAUNTING_ADMIN_PASSWORD=xxx

    - AKAUNTING_BACKUPS_EXPIRY=0
    deploy:
      replicas: 1
    volumes:
    - /swarm/akaunting:/var/lib/akaunting

  nginx:
    image: timeens/akaunting-reverse-proxy:latest
    networks:
      - swarm
    command: app:nginx
    environment:
    - AKAUNTING_PHP_FPM_HOST=akaunting
    - AKAUNTING_PHP_FPM_PORT=9000
    depends_on:
    - akaunting
    deploy:
      replicas: 1
      labels:
        - traefik.enable=true
        - traefik.http.services.akounting.loadbalancer.server.port=80
        - traefik.http.routers.akounting.rule=Host(`akaunting.xxx`)
        - traefik.http.routers.akounting.entrypoints=websecure
        - traefik.http.routers.akounting.tls.certresolver=letsencryptresolver
    
networks:
  swarm:
    external: true
`

**Comment by stefanDeveloper** [comment]
@timeens Works like a charm. Thanks for your help

**Comment by wuujiann** [comment]
I encountered the same problem using traefik proxy.  Managed to find the solution from Akaunting's doc [https://akaunting.com/docs/developer-manual/reverse-proxy](https://akaunting.com/docs/developer-manual/reverse-proxy)

**Below are the steps I followed to fix the problem**
1. Go into the akaunting container
`docker exec -it acct_akaunting_1 bash `
2. Publish TrustedProxy package
`php artisan vendor:publish --provider="Fideloper\Proxy\TrustedProxyServiceProvider"`
3. Edit `config/trustedproxy.php` file (in my case, the full path is `/var/www/akaunting/config/trustedproxy.php`).  Since 'vi' or 'nano' is not available in the docker container, I used 'sed' command to modify the 'proxy' line.
`cat config/trustedproxy.php | sed "s/# 'proxies' => '\*'/'proxies' => '*'/" > /tmp/trustedproxy.php`
4. Ensure that the changes made is correct:
`diff config/trustedproxy.php /tmp`
`35c35`
`<      # 'proxies' => '*',`
`---`
`>      'proxies' => '*',`
5. Replace the `trustedproxy.php` file with the modified one
`mv /tmp/trustedproxy.php config` 

**NOTE:** Please ensure that **https** is used for `AKAUNTING_URL` in _docker-compose.yml_ file.  E.g., `- AKAUNTING_URL=https://xxx`
